export const profileSetupContent = {
  shell: {
    brandName: 'Meridian',
    brandInitial: 'M',
    brandAriaLabel: 'Meridian onboarding home',
    progressName: 'Profile setup',
    footerTitle: 'Meridian employee onboarding',
    footerMode: 'Demo experience',
  },
  welcome: {
    eyebrow: 'Your first days at Meridian',
    title: 'A clearer start begins here.',
    description:
      'Meet the people you will work with, understand how the company works, and arrive on your first day knowing what comes next.',
    action: 'Begin onboarding',
    supportingNote: 'It only takes a moment to find your profile.',
    journeyAriaLabel: 'What to expect',
    journeyLabel: 'A thoughtful first step',
    journey: [
      {
        number: '01',
        title: 'Find your profile',
        description: 'Use your name to locate your Meridian details.',
      },
      {
        number: '02',
        title: 'Confirm it is you',
        description: 'Review your role, team, and manager.',
      },
      {
        number: '03',
        title: 'Start with confidence',
        description: 'Continue into your personalized company guide.',
      },
    ],
  },
  findProfile: {
    back: 'Back',
    eyebrow: "Let's find you",
    title: 'What is your name?',
    description: "Enter your name as it appears in Meridian's employee directory.",
    firstNameLabel: 'First name',
    firstNamePlaceholder: 'Daniel',
    lastNameLabel: 'Last name',
    lastNamePlaceholder: 'Dumitru',
    submit: 'Find my profile',
    submitting: 'Searching…',
    requestError: 'We could not reach the employee directory. Please try again.',
    emptyTitle: 'No matching profile found.',
    emptyDescription: 'Check the spelling or contact HR for help.',
    resultsLabel: (count: number) =>
      count === 1 ? 'We found your profile' : 'Choose your profile',
  },
  confirmProfile: {
    unavailableEyebrow: 'Profile unavailable',
    unavailableTitle: "We couldn't load this profile.",
    unavailableDescription: 'Return to the search and choose an employee again.',
    unavailableAction: 'Back to search',
    loading: 'Loading your Meridian profile…',
    confirmedEyebrow: 'Profile confirmed',
    confirmedTitle: (firstName: string) => `Welcome, ${firstName}.`,
    confirmedDescription:
      'Your profile is ready. The personalized onboarding journey comes next.',
    nextLabel: 'Up next',
    nextTitle: 'Your first day at Meridian',
    nextAction: 'Continue to onboarding',
    back: 'Not you? Search again',
    eyebrow: 'One last check',
    title: 'Is this you?',
    description: 'Confirm these details before entering your onboarding experience.',
    teamLabel: 'Team',
    managerLabel: 'Manager',
    missingManager: 'To be confirmed',
    startDateLabel: 'Start date',
    emailLabel: 'Work email',
    action: 'Yes, this is me',
    demoNotice: 'Demo mode does not verify your identity or grant secure access.',
  },
} as const
